<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>False</UseWindowsForms>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Content\Animation\BallisticsFX\BulletDebug.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud01.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud02.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud03.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud04.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud05.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud06.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud07.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud08.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud09.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud10.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud11.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud12.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud13.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud14.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud15.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud16.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud17.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud18.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud19.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud20.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_000.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_001.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_002.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_003.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_004.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_005.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_006.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_007.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_008.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_009.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_010.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_011.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_012.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_013.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_014.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_015.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_016.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_017.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_018.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_019.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_020.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_021.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_022.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_023.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_024.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_025.png" />
    <None Remove="Content\Animation\Rifle\SVLK14S\T_Scope_Lens.png" />
    <None Remove="Content\checkmark.png" />
    <None Remove="Content\Lobby\T_MapPreview_Combined.png" />
    <None Remove="Content\Lobby\T_MapPreview_Fog.png" />
    <None Remove="Content\Lobby\T_MapPreview_Sun.png" />
    <None Remove="Content\Lobby\T_MapPreview_Sunset.png" />
    <None Remove="Content\Animation\BallisticsFX\CommonTracer\T_Tracer_Common01.png" />
    <None Remove="Content\Animation\BallisticsFX\CommonTracer\T_Tracer_Common02.png" />
    <None Remove="Content\Animation\BallisticsFX\CommonTracer\T_Tracer_Common03.png" />
    <None Remove="Content\Animation\BallisticsFX\CommonTracer\T_Tracer_Common04.png" />
    <None Remove="Content\Enemy\Test_Enemy.png" />
    <None Remove="Content\Enemy\Test_Enemy_Coll.png" />
    <None Remove="Content\Maps\Depth\W001.png" />
    <None Remove="Content\Maps\Foggy\W001.png" />
    <None Remove="Content\Maps\Sunny\W001.png" />
    <None Remove="Content\Maps\Sunset\W001.png" />
    <None Remove="Content\Maps\Test\Test_D.png" />
    <None Remove="Content\Maps\Test\Test_W.png" />
    <None Remove="Content\ui\T_CrossAIM.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud01.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud02.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud03.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud04.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud05.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud06.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud07.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud08.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud09.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud10.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud11.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud12.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud13.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud14.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud15.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud16.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud17.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud18.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud19.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud20.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_000.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_001.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_002.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_003.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_004.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_005.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_006.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_007.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_008.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_009.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_010.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_011.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_012.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_013.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_014.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_015.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_016.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_017.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_018.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_019.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_020.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_021.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_022.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_023.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_024.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\A_Zooming\A_Zooming_025.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\SVLK14S\T_Scope_Lens.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\checkmark.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Lobby\T_MapPreview_Combined.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\BallisticsFX\BulletDebug.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\BallisticsFX\CommonTracer\T_Tracer_Common01.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\BallisticsFX\CommonTracer\T_Tracer_Common02.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\BallisticsFX\CommonTracer\T_Tracer_Common03.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\BallisticsFX\CommonTracer\T_Tracer_Common04.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Enemy\Test_Enemy.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Enemy\Test_Enemy_Coll.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Maps\Depth\W001.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Maps\Foggy\W001.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Maps\Sunny\W001.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Maps\Sunset\W001.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Maps\Test\Test_D.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Maps\Test\Test_W.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\ui\T_CrossAIM.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.13.0.20260302" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Content\Lobby\T_MapPreview_Fog.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Lobby\T_MapPreview_Sun.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Lobby\T_MapPreview_Sunset.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\shared\VLSShared\VLSShared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Config\GameSettings.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Content\Animation\BallisticsFX\" />
    <Folder Include="Rendering\Content2D\HUD\" />
  </ItemGroup>

</Project>
