<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>False</UseWindowsForms>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Content\Animation\BallisticsFX\BulletDebug.png" />
    <None Remove="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud01.png" />
    <None Remove="Content\checkmark.png" />
    <None Remove="Content\Lobby\T_MapPreview_Combined.png" />
    <None Remove="Content\Lobby\T_MapPreview_Fog.png" />
    <None Remove="Content\Lobby\T_MapPreview_Sun.png" />
    <None Remove="Content\Lobby\T_MapPreview_Sunset.png" />
    <None Remove="Content\Animation\BallisticsFX\CommonTracer\T_Tracer_Common01.png" />
    <None Remove="Content\Animation\BallisticsFX\CommonTracer\T_Tracer_Common02.png" />
    <None Remove="Content\Animation\BallisticsFX\CommonTracer\T_Tracer_Common03.png" />
    <None Remove="Content\Animation\BallisticsFX\CommonTracer\T_Tracer_Common04.png" />
    <None Remove="Content\Animation\Rifle\Test_Debug_Scope.png" />
    <None Remove="Content\Enemy\Test_Enemy.png" />
    <None Remove="Content\Enemy\Test_Enemy_Coll.png" />
    <None Remove="Content\Maps\Test_D.png" />
    <None Remove="Content\Maps\Test_W.png" />
    <None Remove="Content\ui\T_CrossAIM.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Content\Animation\PlayerFX\BloodHit\T_Hit_Cloud01.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\checkmark.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Lobby\T_MapPreview_Combined.png">
	</Content>
    <Content Include="Content\Animation\BallisticsFX\BulletDebug.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\BallisticsFX\CommonTracer\T_Tracer_Common01.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\BallisticsFX\CommonTracer\T_Tracer_Common02.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\BallisticsFX\CommonTracer\T_Tracer_Common03.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\BallisticsFX\CommonTracer\T_Tracer_Common04.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Animation\Rifle\Test_Debug_Scope.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Enemy\Test_Enemy.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Enemy\Test_Enemy_Coll.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\ui\T_CrossAIM.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.13.0.20260302" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Content\Maps\Test_D.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Maps\Test_W.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Content\Lobby\T_MapPreview_Fog.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Lobby\T_MapPreview_Sun.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\Lobby\T_MapPreview_Sunset.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\shared\VLSShared\VLSShared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Config\GameSettings.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Content\Animation\BallisticsFX\" />
  </ItemGroup>

</Project>
